### PR TITLE
Add Xs Watch support (with async support)

### PR DESCRIPTION
**Pull request by TSnake41**
Replaces #11

### CODE REVIEW

**Comment by ydirson** [comment]
Fixed my faulty rebase caused by `clap` being converted to dev-dependency in the `xs_write` PR.

**Comment by Wenzel** [comment]
@TSnake41 this PR seems to have conflicts now
I introduced format checks in the CI wtih #15 , can you `cargo fmt` your code and update this PR ?
Thanks !

**Comment by Wenzel** [comment]
@TSnake41 can you rebase this one please ?
There are some merge conflicts and this PR doesn't allow edit from maintainers.

**Comment by Wenzel** [comment]
LGTM

**Pull request merged**
